# Johdanto

## Alkutoimia

Ero YAML-headerissa lang-parametri (lang: fi). (verrattuna bookdown-demoon).
Bookdown-demossa lisäksi output: pdf_document, mutta lienee tarpeeton kun kaksi outputformaattia annettu output.yaml-tiedostossa

Bookdown - formaatissa "juuritiedoston" indexBD.Rmd tekstit eivät tulostu jos siellä ei ole luvun (chapter) aloittavaa ensimmäisen tason otsikkoa. Siellä on YAML-headeri (metadata).

Lisää YAML-parametreja voi antaa tiedostoissa _bookdown.yml ja _output.yml. Nämä lienee välittyvät Pandocille?

Bookdown - demon esimerkkitiedostot ovat nämä:

ouput.yml (huomaa, että _ - merkki jätetty pois!) (tässä oli bookdown-demo-paketin yml-tiedostot, poistin 3.7.2018)

## Tärkeimmät ohjelmistot

```{r bdprogs1, echo=TRUE}
system("pdflatex --version")
rmarkdown::pandoc_version()

```

Viimeinen rivi kertoo pandoc-version.
**20.9.2019** Pandoc-versio tulostuu oikein, mutta pdf-latex - komennon tulosteesta
vain viimeinen rivi. Tässä konsolilta kopioitu 7.6.2020

MiKTeX-pdfTeX 2.9.7338 (1.40.21) (MiKTeX 2.9.7400 64-bit)
Copyright (C) 1982 D. E. Knuth, (C) 1996-2020 Han The Thanh
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.61.1; using libcurl/7.61.1 WinSSL
compiled with expat version 2.2.6; using expat_2.2.6
compiled with jpeg version 9.3
compiled with liblzma version 50020042; using 50020042
compiled with libpng version 1.6.37; using 1.6.37
compiled with libressl version LibreSSL 2.8.2; using LibreSSL 2.8.2
compiled with MiKTeX Application Framework version 4.7414; using 4.7414
compiled with MiKTeX Core version 18.7414; using 18.7414
compiled with MiKTeX Archive Extractor version 1.6882; using 1.6882
compiled with MiKTeX Package Manager version 9.7414; using 9.7414
compiled with poppler version 0.60.1
compiled with uriparser version 0.9.2
compiled with zlib version 1.2.11; using 1.2.11


##  Muutoksia, tilannetietoja ja puutteita

Tulostusformaatteina testataan gitbook ^[Virheilmoitukset ovat aika hyödyttömiä.
Tähän alkuun sopisi kuvaus perusideoista ja tekstin muotoiluista. Alaviitteistä esimerkiksi.]
ja pdf_book. Molemmat ovat html-paketteja, ja tarvitsevat ehkä r-datahakemistosta
(omalta koneelta) libs-hakemiston jQuery- ja Gitbook-paketit (javaskriptiä ja css-tyylitiedostoja)
**edit: gitbook on html/CSS/javascript-paketti (3.10.20)**.

test1_preamble.tex -tiedostolla voi säätää Tex-asetuksia. Tuo ei toimi, mutta
simple_peambe.tex - toimii (luvun nimi pois sivun ylälaidasta).

Lähdeluettelossa Å tulee heti A - kirjaimen jälkeen gitbook-versiossa.
PDF-tiedostossa taas Å-alkuinen sukunimi sijoittuu vähän toisin virheellisesti.
Ikävä juttu!

